services:
  # Container 1: The Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ev_admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=ev_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # This saves your data even if the container dies!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ev_admin -d ev_database"]
      interval: 5s
      timeout: 5s
      retries: 5
  # Container 2: The FastAPI Backend
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # This tells the API exactly how to log into the database container
      - DATABASE_URL=postgresql://ev_admin:supersecret@db:5432/ev_database
    volumes:
      - .:/code # "Hot Reload" mapping - links the local VS Code files to the container
    depends_on:
      db:
        condition: service_healthy

# Define the persistent storage drive
volumes:
  postgres_data: